sudo: required
services: 
    - docker

before_install:
    - docker build -t alexkhodorenko/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alexkhodorenko/docker-react npm run test -- --coverage